package cn.locusc.retry.task.domain;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * @author jayChan
 * 重试任务实体类
 * 2021/5/14
 **/
@Data
public class RetryTask implements Serializable {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RETRY_TASK
     */
    private static final long serialVersionUID = 1L;

    /**
     * 主键
     */
    private Integer id;

    /**
     * 最大重试次数
     */
    private Integer maxAttempts;

    /**
     * 重试方法路径
     */
    private String methodInfo;

    /**
     * 状态
     */
    private Integer retryStatus;

    /**
     * 创建时间
     */
    private Date createDate;

    /**
     * 更新时间
     */
    private Date updateDate;

    /**
     * 当前重试次数
     */
    private Integer currentAttempts;

    /**
     * 最大休眠时间
     */
    private Integer maxInterval;

    /**
     * 任务名
     */
    private String taskName;

    /**
     * 平台号
     */
    private String platNo;

    /**
     * 判断任务是否存在以及有效
     */
    private Integer isDel;

    /**
     * 重试后返回的结果
     */
    private String responseData;

    /**
     * 错误信息
     */
    private String exceptionJson;

    /**
     * 入参信息
     */
    private String retryParams;

    /**
     * 重试规则
     **/
    private String retryRule;

}